sudo: required
language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
before_install:
  - docker pull ansi/mosquitto
  - docker run -d -p 1884:1883 ansi/mosquitto
jobs:
  include:
    - stage: test
      name: "OracleJDK 8"
      jdk: oraclejdk8
      script: mvn -q clean verify -Dmqtt.server.host=localhost -Dmqtt.server.port=1884 -B
    - if: type != pull_request
      name: "OpenJDK 11"
      jdk: openjdk11
      script: mvn -q clean verify -Dmqtt.server.host=localhost -Dmqtt.server.port=1884 -B
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request
      script: bash .travis.deploy.artifacts.sh
services:
  - docker
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
